[package]
name = "contract-solana"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18"

[dev-dependencies]
solana-sdk = "1.18"
solana-program-test = "1.18"

[lib]
crate-type = ["cdylib", "lib"]
